### ISSUE TITLE
reactNativeKakaoLogins2.default.login

### ISSUE THREAD

**Issue by hotshine** [react-native-seoul/react-native-kakao-logins#1]
안녕하세요~
카카오 로그인 모듈 샘플 예제 실행시 ios 와 안드로이드 동일하게
undefined is not an object (evaluating '_reactNativeKakaoLogins2.default.login.default.login')
에러가 나는데요
올려주신 샘플소스 확인 가능하실지 문의드립니다.

**Comment by dooboolab** [comment]
@hotshine 헛 확인이 늦었네요.. 그동안 여러가지 이유로 maintain이 안되고 있었고 이제서야 작업에 들어갔습니다.. 안드로이드만 구현이 되었고 ios는 구현중입니다..

**Comment by dooboolab** [comment]
@hotshine ios 구현 완료하였습니다.
