### ISSUE TITLE
Read me에 있는 manual installation이 무슨 말인지 모르겠습니다.

### ISSUE THREAD

**Issue by liamstory** [react-native-seoul/react-native-kakao-logins#11]
1.In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
 => Xcode를 열고 project navigator에서 오른쪽 클릭하여 Add Files to project name해서 여기서 다운 받은 파일 추가
2.Go to node_modules ➜ react-native-kakao-logins and add RNKakaoLogins.xcodeproj
=>react-native 내의 node_modules에 react-native-kakao-logins와 RNKakaoLogins.xcodeproj 복사 붙여넣기

3.In XCode, in the project navigator, select your project. Add libRNKakaoLogins.a to your project's 
=>add libRNKakaoLogins.a라는게, libRNKaKaoLogins.a 파일을 새로 만들어서 넣어라는건가요? 올려주신 파일중에는 다음과 같은 명의 파일이 없어서요

4.Build Phases ➜ Link Binary With Libraries
5.Run your project (Cmd+R)<

**Comment by dooboolab** [comment]
@liamstory RN 프로젝트에 네이티브 모듈을 링킹하는 방법입니다. [링크](https://facebook.github.io/react-native/docs/linking-libraries-ios)를 참고해주세요.
