### ISSUE TITLE
undefined is not an object (evaluating 'RNKakaoLogins.login')

### ISSUE THREAD

**Issue by liamstory** [react-native-seoul/react-native-kakao-logins#12]
안녕하세요~
카카오 로그인 모듈 샘플 예제 실행시 ios에서
undefined is not an object (evaluating 'RNKakaoLogins.login')
에러가 나는데요
올려주신 샘플소스 확인 가능하실지 문의드립니다.

**Comment by dooboolab** [comment]
@liamstory 방금 시도해봤는데 정상적으로 잘 됩니다. 혹시 `npm install`을 안하신건 아닌가요? 아니면 `node_modules`를 다시 설치하시고 새로 실행해봐주세요.

**Comment by liamstory** [comment]
제 실수가 있었네요 답변 감사합니다.!
