### ISSUE TITLE
accessToken response is non Json

### ISSUE THREAD

**Issue by Bang9** [react-native-seoul/react-native-kakao-logins#14]
ios로 연결중인데, login이후 들어오는 액세스토큰의 값이 Json타입이 아닌 String객체로 들어옵니다.
"{"token":"abcdefg"}" 형태가 아니라 "{token :abcdefg}" 다음과 같이 들어와서 parse해서 바로 쓰지 못합니다.

**Comment by dooboolab** [comment]
@Bang9 안녕하세요. 이슈 리포트 감사드립니다. 음 간단하게 해결할 수 있는 문제로 보이는데 혹시 contribute를 한번 도전해보시는 것이 어떨까요? 제가 수정해도 되지만 좋은 문화를 위해서 많은 분들께 기회를 드리려고 합니다.

**Comment by Bang9** [comment]
스위프트 공부하려고 했는데 한번 보고 수정 후 PR날려볼게요 :)

**Comment by dooboolab** [comment]
[수정](https://github.com/react-native-seoul/react-native-kakao-logins/pull/15) 되었습니다.
