### ISSUE TITLE
fatal error: 'KakaoOpenSDK/KakaoOpenSDK.h' file not found

### ISSUE THREAD

**Issue by byunghyunpark** [react-native-seoul/react-native-kakao-logins#2]
react-native link react-native-kakao-logins 명령으로 링크를 하면 
react-native run-ios 명령으로 시뮬레이터 구동 시, 아래와 같은 에러가 발생합니다.

/Users/pbh/project/react/KakaoLoginTest2/node_modules/react-native-kakao-logins/ios/RNKakaoLogins.m:4:9: fatal error: 'KakaoOpenSDK/KakaoOpenSDK.h' file not found
#import <KakaoOpenSDK/KakaoOpenSDK.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

제 프로젝트에 적용하다가 해결이 안되서
기본 프로젝트로 본 패키지만 설치해봤는데
링크 후 동일한 에러가 발생합니다.

어떤게 문제일까요?

**Comment by byunghyunpark** [comment]
카카오 페이지에서 SDK 별도로 받아서 프로젝트에 넣으니 정상 작동합니다

**Comment by skout90** [comment]
@byunghyunpark 감사합니다 저도 해당 케이스 발생했는데 덕분에 해결했습니다!!
