### ISSUE TITLE
Android에서 Expokit을 사용 중일때 적용 문제

### ISSUE THREAD

**Issue by cheolhow** [react-native-seoul/react-native-kakao-logins#23]
Expokit을 사용하면 MainApplication.java에서는
```
public class MainApplication extends ExpoApplication
```
와 같이 ExpoApplication를 이미 상속 받아서 사용합니다.

안드로이드에서 com.dooboolab.kakaologins.GlobalApplication를 MainApplication이 상속받을 수가 없는데 어떻게 해야할까요?

**Comment by dooboolab** [comment]
@cheolhow 안녕하세요~
그런 경우 보통 자바에서는 `interface`를 만들어서 다중 상속을 받습니다.
class는 하나의 class밖에 상속받을 수 없지만 interface는 다중상속을 지원합니다.
