### ISSUE TITLE
The example code doesn't work for me

### ISSUE THREAD

**Issue by drake-jin** [react-native-seoul/react-native-kakao-logins#27]
# error case 1

When I open the project on AndroidStudio. Gradle has occurred a problem. like this below the image.

https://github.com/corymsmith/react-native-fabric/issues/200

# Suggestion

- before
``` gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

(...)
```

- after
``` gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

(...)
```

# error case 2

I read the README.md about this project, but this example code follows a legacy version.
So, This example can't resolve the class that name 'GlobalApplication' at android.
I think you'd better maintain this example. kind regards.

**Comment by dooboolab** [comment]
Please put the jcenter at the very bottom. Recent Android version has issue with this one so you must put that to very bottom currently.
