### ISSUE TITLE
Security alert in Google Play Console: Vulnerable WebView to Cross App Scripting

### ISSUE THREAD

**Issue by FlorianBergmann** [react-native-seoul/react-native-kakao-logins#30]
When using this library and uploading an apk to the Google Play Console there is an alert that the app includes a WebView that is vulnerable to cross app scripting. More info can be found under https://support.google.com/faqs/answer/9084685

The vulnerable class is:
com.kakao.auth.authorization.authcode.KakaoWebViewActivity->initUi

**Comment by FlorianBergmann** [comment]
We also have an app that is written in Java that is using the Kakao sdk but there the is no alert. We are using version `1.1.28` in the Java app so it might be dependent on the version.

**Comment by dooboolab** [comment]
@FlorianBergmann Yeah. Then we can upgrade kakao sdk later.

**Comment by hyochan** [comment]
I've released new kakaosdk just now with `1.15.1` try this.
