### ISSUE TITLE
[QUESTION] Android kakao sdk upgrade 관련 질문 

### ISSUE THREAD

**Issue by heyman333** [react-native-seoul/react-native-kakao-logins#32]
안녕하세요
최근에 kakao sdk version을 1.15.X로 올리셨던데
혹시 https://devtalk.kakao.com/t/topic/61304/2
이 문제로 인한 버전업인가요~?

**Comment by hyochan** [comment]
#30 관련하여 업그레이드를 진행해보았습니다.

**Comment by heyman333** [comment]
@hyochan 아 그러시군요. 최신 버전으로 다시 카카오 sdk를 설치한 뒤에도 풀레이스토어에서 경고창이 뜨는 것으로 보아 문제가 남아 있는 것처럼 보이는데, 혹시 제가 뭘 놓치고 있는 부분이나 참고 할만하 내용이 있을까요!??

**Comment by hyochan** [comment]
글쎄요 요청이 있어서 업글을 진행하였지만 아직 정확한 해결방법은 모르겠네요~

**Comment by heyman333** [comment]
@hyochan 아 그러시군요! 방법을 찾아보려고 하니 해결되면 PR보내겠씁니다!

**Comment by heyman333** [comment]
@hyochan 카카오측에서 문제를 해결한 버전인 1.15버전으로 빌드가 빌드가 됐음에도 불구하고 왜 구글에서 경고를 계속 주는지는 모르겠네요,,,구글 플레이 콘솔 문제일 수도 있을거같습니다...
