### ISSUE TITLE
kakaoLogin() 이 실행되고 로그인이 완전히 실행 된후 getProfile() 함수를 부르는 방법에 관해 질문 드립니다.

### ISSUE THREAD

**Issue by yunjay** [react-native-seoul/react-native-kakao-logins#43]
getProfile 함수를 아래와 같이 하여 state에 프로필사진의 경로를 저장하는 방식 등으로 라이브러리를 사용하고자 합니다. async/await 등의 방법으로 시도를 하였지만 로그인을 실행하는 이벤트와 getProfile을 실행하는 이벤트를 따로 onPress 등에 넣지 않고 한번의 이벤트로 비동기방식으로 두가지를 실행 시키는 방법을 찾지 못하고 있습니다. 혹시 이에 관해 답해주시면 감사하겠습니다. (kakaoLogin()으로 로그인 이후에 getProfile()로 state에 getProfile의 result의 json 값들을 저장시키는 방법을 묻습니다ㅠ)
```
getProfile() {
   RNKakaoLogins.getProfile((err, result) => {
      if (err) {
        Alert.alert("error profile", JSON.stringify(err));
        return;
      }
    this.setState({ isLoggedIn: true, image: result.profile_image_path });
    });
  }
```

**Comment by hwan27** [comment]
저도 카카오로그인을 하면서 동시에 프로필 정보를 얻어와 갱신하는게 안되네요. 고수님들의 답변 기대합니다 ㅠ

**Comment by SungNahyun** [comment]
도움이 될 지 모르겠지만 저는 이런식으로 구현하였습니다.

` kakaoLogin() {
    RNKakaoLogins.login( async (err, result) => {
      if (result !== null && result !== undefined) {
        try {
          const profile = await this.getProfile();
          if (profile.success) {  // 프로필 받아오기 성공
          // 프로필정보를 받아온 후 해야할 것들을 합니다.
          } else throw profile.result;
        } catch (error) { console.log('[KakaoLogins.getProfile] error :', error); }
      }
      if (err) {
        console.log('[RNKakaoLogins.login] ', err);
        return;
      }
    });
  }

getProfile() {
    return new Promise ((resolve, reject) => {
      RNKakaoLogins.getProfile((err, result) => {
        if(result !== null && result !== undefined){ resolve({success: true, result: result}) }
        if (err) { reject({success: false, result: err}) }
      });
    })
  }
`
