### ISSUE TITLE
다른 카카오계정으로 로그인 오류??

### ISSUE THREAD

**Issue by gilra2000** [react-native-seoul/react-native-kakao-logins#45]
한번 카카오 로그인 후 
다른 카카오계정 로그인 호출 시 계정입력 하는 창이 나오지 않고
토큰값을 바로 리턴해버리네요.. 
뭐가 문제인가요?

**Comment by hyochan** [comment]
로그인 이후 세션이 살아있어서 그런 것 같은데요. `Logout`을 해보시고 다시 시도해보세요~ 이후에도 문제가 있으시면 이슈를 다시 열겠습니다.

**Comment by pitchitmaster101** [comment]
로그아웃 상태에서 위와 같은 문제가 발생하였습니다. 다른 계정으로 로그인을 시도하였으나 바로 토큰이 리턴되었습니다. 
1. 제가 직접 수정할수 있는 여지가 있는지 궁금합니다. 
2. 혹은 다른계정으로 로그인 버튼을 없앨수 있는 방법이 있는지도 궁금합니다.

(유용한 라이브러리 정말 감사히 쓰고있습니다.)
