### ISSUE TITLE
[android] Value for message cannot be cast from ReadableNativeMap to string 에러

### ISSUE THREAD

**Issue by jihyeonjeong11** [react-native-seoul/react-native-kakao-logins#47]
좋은 라이브러리 감사합니다.
질문이 하나 있어 남겨드립니다.
RNKakaoLogins.login() 호출 시 해당 기능은 잘 작동하지만 (기존 카카오 로그인, 다른 계정으로 로그인 등 modal 표시)

로그인 성공 시 이후 코드가 실행되지 않고 위 제목의 에러가 발생합니다.
Value for message cannot be cast from ReadableNativeMap to string

감사합니다.

**Comment by jihyeonjeong11** [comment]
해결했습니다.
결과를 alert으로 객체를 표시하려다 보니 생기는 오류로 example code에서 alert 부분을 console.log 로 바꾸었습니다.
다시 한번 감사합니다.

**Comment by duboo** [comment]
제가 현재 카카오로그인 활용시 그 에러가 나고 있는데 저는 alert를 console.log로 바꿨더니 에러는 사라졌지만 기능이 반응하질 않네요ㅠㅠ 카카오톡으로 로그인 후 사용자 정보를 받아서 홈화면에 사용자 정보 (ex)이름을 띄우고 싶은데 혹시 참고 코드가 있을까요??

**Comment by heyman333** [comment]
@duboo 저희 예제코드가 그렇게 되어 있습니다.
https://github.com/react-native-seoul/react-native-kakao-login/blob/master/KakaoLoginExample/App.js
