### ISSUE TITLE
카카오 ios 로그아웃시 result 값이 안나옵니다. 

### ISSUE THREAD

**Issue by kirhim** [react-native-seoul/react-native-kakao-logins#57]
ios 에서 로그인은 잘되는데 로그아웃 할 때 err값은 나오는데 result 값이 안나옵니다.

왜 그러는지 알 수 있을까요?

**Comment by kirhim** [comment]
@sunkibaek method description 보면 `callback (err: string, result: string)` 이렇게 나와있는데 err는 로그아웃이 안됬을때 err값을 나타내는거고 result 값은 로그아웃 성공시 나오는거 아닌가요?

**Comment by heyman333** [comment]
#55 참고 해주시면 감사하겠습니다~
