### ISSUE TITLE
최신 버전 릴리즈

### ISSUE THREAD

**Issue by sunkibaek** [react-native-seoul/react-native-kakao-logins#59]
master 브랜치의 내용이 아직 npm 으로 publishing되지는 않은 것 같은데요 publishing부탁 드립니다~ 🙏 ㅎㅎ

@hyochan

**Comment by hyochan** [comment]
@sunkibaek 안녕하세요 오랜만입니다 ㅎㅎ. 방금 `1.3.8`로 릴리즈 했습니다 감사합니다 ㅜ

**Comment by hyochan** [comment]
@sunkibaek  캐나다 라이프는 어떠신지요? 방금 `collaborator`로 혹시 몰라 초대 드렸어요. 앞으로 이슈 대응에 더 힘을 써보도록 하겠습니다!

**Comment by hyochan** [comment]
@sunkibaek 그렇군요 ㅎㅎ 많이 바쁘신 것 같은데 이렇게 뵈니 너무 좋네요 :) 현재 여기 레포에는 네이버 / 카카오 로그인만 유지되고 있는 것 같아요. 제가 현 레포는 신경을 많이 못 써서 0.60 (androidx) 대응 이슈도 있는 것 같고요.

저희 밋업에서는 [@dooboo-ui/native](https://github.com/dooboolab/dooboo-ui-native) 이 레포에 `ui-component`들 만들어서 기여하고 있어요~ `shared` compoenent들만 `npm`에 배포되고요. 이것도 참고해주시면 좋을 것 같아요 😄

**Comment by sunkibaek** [comment]
@hyochan 오 그렇군요~ 한 번 살펴볼게요~

**Comment by hyochan** [comment]
넵 이제 막 걸음마 단계라서 아직까진 별개 없습니다 ㅎㅎ `Gihub`에서 자주 뵐 수 있는 기회가 될 수도 있을 것 같네요 😃
