### ISSUE TITLE
카카오 로그인 팝업 영문...?

### ISSUE THREAD

**Issue by vgb0332** [react-native-seoul/react-native-kakao-logins#60]
로그인 팝업이 영문으로 나오는데 혹시 이건 제가 앱 설정을 잘못한걸까요?

**Comment by heyman333** [comment]
카카오 UI에서 워딩이 영문으로 나온다면 아마 기본 디바이스 설정이 그래서 그럴 수도 있습니다~
한번 실제 사용하고 있는 디바이스에 테스트 해보셨나요?

**Comment by vgb0332** [comment]
아 넵 맞습니다. 모듈 문제는 아니고, 핸드폰 언어 설정 문제였네요..클로징 한다는게 깜빡하고 올려두었네요. 그래도 소중한 답변 감사합니다!
