### ISSUE TITLE
npm install 시 뜨는 에러

### ISSUE THREAD

**Issue by vgb0332** [react-native-seoul/react-native-kakao-logins#62]
RN version: 0.60.5
Xcode version : 11(latest)
OS: IOS
Simulator: Iphone X

react-native-kakao-logins 모듈 자체에 문제는 없습니다!
다만 작업 중 새로운 패키지 npm install 시 다음과 같은 에러가 계속 생겨서 메뉴얼로 rm -rf node-modules/react-native-kakao-logins 이후 다시 npm install <new package>를 하고 있는데,
이를 없앨 수 있는 원인을 알고 싶네요..

에러는 다음과 같습니다.
Markui-MacBookPro:drsalary_app mj$ npm install react-native-calendars
npm ERR! path /Users/mj/Desktop/projects/drsalary_app/node_modules/react-native-kakao-logins
npm ERR! code EISGIT
npm ERR! git /Users/mj/Desktop/projects/drsalary_app/node_modules/react-native-kakao-logins: Appears to be a git repo or submodule.
npm ERR! git     /Users/mj/Desktop/projects/drsalary_app/node_modules/react-native-kakao-logins
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mj/.npm/_logs/2019-09-25T03_13_18_643Z-debug.log

**Comment by heyman333** [comment]
안녕하세요 저도 어제 이문제를 인지했구요,
PR을 보내놨으니 merge되면 해결 될 것 같습니다~
